change logging level + move vars to default
AerisCloud/ansible-zookeeper pull request #8
Opened 2016-10-11 07:26 UTC by tokyowizard

This PR allows to change the default logging level, `INFO`, to [user assigned level](http://logging.apache.org/log4j/1.2/manual.html#Logger_hierarchy).

The set of possible levels, that is:

`TRACE`,
`DEBUG`,
`INFO`,
`WARN`,
`ERROR` and
`FATAL`

2016-10-11 07:37 UTC, MiLk requested changes

2016-10-11 07:37 UTC, MiLk commented on README.md
> +# Optional. Change the logging level.
Could you add a link to the documentation with the list of valid values?

2016-10-11 07:37 UTC, MiLk commented on tasks/centos.yml
> +  when: ansible_distribution_major_version|int >= 7
If these options are defined here, maybe they should be removed from `/etc/zookeeper/conf/zoo.cfg`.

2016-10-11 07:40 UTC, tokyowizard commented on README.md
> +# Optional. Change the logging level.
Thanks! I've added the link just below that line.

2016-10-11 07:40 UTC, tokyowizard commented on tasks/centos.yml
> +  when: ansible_distribution_major_version|int >= 7
Thanks! Good idea. I've removed it from `zoo.cfg`

2016-10-11 07:46 UTC, MiLk requested changes

2016-10-11 07:46 UTC, MiLk commented on tasks/centos.yml
> +  when: ansible_distribution_major_version|int >= 7
Hum, they should be kept for Debian and Centos 6, no?

2016-10-11 11:56 UTC, tokyowizard commented on tasks/centos.yml
> +  when: ansible_distribution_major_version|int >= 7
Fixed for CentOS 6.

2016-10-14 11:25 UTC, MiLk requested changes

2016-10-14 11:25 UTC, MiLk commented on tasks/debian.yml
> +- fail: msg="The ZooKeeper Playbook does not support Ubuntu"
Debian

2016-10-14 12:19 UTC, tokyowizard commented on tasks/debian.yml
> +- fail: msg="The ZooKeeper Playbook does not support Ubuntu"
Thanks. fixed.

2016-10-15 02:12 UTC, MiLk approved these changes

2016-10-15 02:12 UTC, merged